# Generated by Django 3.2.25 on 2024-04-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ispremium',
            new_name='is_premium',
        ),
    ]
