# Generated by Django 3.2.25 on 2024-04-25 10:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
